[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Domain redirects should come FIRST (before the catch-all)
[[redirects]]
  from = "https://rahulnayanegali.netlify.app/*"
  to = "https://rahulnayanegali.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://rahulnayanegali.netlify.app/*"
  to = "https://rahulnayanegali.dev/:splat"
  status = 301
  force = true

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/twitter/*"
  to = "/.netlify/functions/twitter/:splat"
  status = 200

# This catch-all should be LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200